### ISSUE TITLE
Possible Gotcha if NOT using RADDS

### ISSUE THREAD

**Issue by ghost** [luc-github/DUE-RADDS-GLCD#1]
Hi

Your advice has been immensely valuable in getting a GLCD running on my own Due based board.

Just a little note for some other developers that might end up bumping their head:

Initially I had endless issues with the encoder either not responding, or going right back to an entry above if I did manage to get it to scroll down one.  After almost half a day of digging I found that if your SDSS pins are NOT 4,10 or 55, then Repetier firmware is compiled with Software SPI.  Software SPI conflicts with the pins you use for the encoder:
# define DUE_SOFTWARE_SPI
# define MOSI_PIN        51
# define MISO_PIN        50
# define SCK_PIN         52
# endif

(:  -  Luckilly I did layout my PCB with SDSS on pin 4 - and my troubles was related to the fact that I copied an existing pin definition and forgot to change its SDSS from 53 to 4...   When I finally saw that missed change, it resolved my issues right away.

But lets leave this here as anyone looking on Google for getting GLCD running on Due (Repetier) - will find your project first (thats how I found it) and it might just save someone some headache

Peter (https://plus.google.com/104034368033227202956/posts)

**Comment by luc-github** [comment]
Hi Thanks - yes that is why I put RADDS in title as I did not really tested on other cards

Additionally the purpose of DUE_SOFTWARE_SPI is to be able to use any pins, so  50/51/52 are just for example I think

what card do you use with your DUE ?  RAMPS-FD or SMART RAMPS ?

**Comment by ghost** [comment]
I spun my own hardware, away from the office this, but will push to github.com/openhardwarecoza over the weekend. (:

I understand yours is RADDS specific, which is why I mention above  "Your advice has been immensely valuable in getting a GLCD running on my _own Due based board_.  Just a little note for some _other developers_ that might end up bumping their head:" - so NB more meant as advice for other board designers to watch out for.  

Software SPI is cool, but hardware SPI is always better - so the NB note to other Dev's here is to not hardwire their encoder to pins 50/51/52 if they intend using software SPI in Repetier, well unless they want to modify the software SPI pins too.  

Either way, hopefully the post helps someone. Your work paved the way for figuring the pinout of the GLCD boards a lot! and your example uiconfig.h, etc as well. I simply used that pinout on my boards to assign Due pins to the 2x 2x5 headers I added for EXP1/2

Here's a photo of the board:

![20150831_125259](https://cloud.githubusercontent.com/assets/7695323/9577252/5cbbf95a-4fdf-11e5-9572-d9a0d85f6389.jpg)

**Comment by luc-github** [comment]
I see 
I look forward to see more about your hardware - any specifications somewhere ? or they will be on github as well ?
I got some strange behaviour with RADDS EEPROM ( several corruptions ), LCD initialization issues which are not present in RAmPS-FD, but as RAMPS-FD is no more supported and current V1 (the one I have) is buggy ,and because I do not feel ready to rework it as V2 based on my limited skills, I look for a replacement which are very limited.... 

So really willing to learn more about your board ^_^

**Comment by ghost** [comment]
Uploaded the project to https://github.com/openhardwarecoza/EvitaBot

**Comment by luc-github** [comment]
thanks you
