### ISSUE TITLE
PCB

### ISSUE THREAD

**Issue by Nandox7** [luc-github/DUE-RADDS-GLCD#3]
Hi,

Found no other way to reach out... :)
Have you just wen the custom cable or or have you tried to make a PCB for this?

I have the exact same issue and was great when I found your docs, my idea was to make a simple adaptor PCB to allow to still use the stock cables.

Cheers

**Comment by luc-github** [comment]
Hi, I did a custom connector /cable, I was too lazy to do a pcb :)

**Comment by Nandox7** [comment]
Is it just direct connection or does it also needs the two resistors (10-20k) you have in the drawing?
I may give this a try and make a PCB for it.

**Comment by luc-github** [comment]
just direct connections - the resistors are supposed to be on LCD board already the picture come from here I think : http://www.dr-henschke.de/LCD_Enc_SD_12.pdf

**Comment by luc-github** [comment]
if no update I close issue
